name: family_tree_app
description: تطبيق شجرة العائلة
publish_to: 'none' # لا يتم النشر على pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sqflite: ^2.2.8+4
  path_provider: ^2.0.15
  graphview: ^1.3.0   # تحديث إلى أحدث إصدار متوافق

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
