name: family_tree_app
description: تطبيق شجرة العائلة (محلي باستخدام SQLite) مع تسجيل دخول وبحث وعرض شجري.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  sqflite: ^2.3.3
  path: ^1.9.0
  provider: ^6.1.2
  graphview: ^1.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true